# Generated by Django 5.0.6 on 2024-06-05 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.CharField(default='No author was added.', max_length=50, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.CharField(default='No tags were added.', max_length=200, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(default='No text was added.', max_length=1000, verbose_name='Quote'),
        ),
    ]
