# Generated by Django 5.0.6 on 2024-06-05 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post_post_author_post_post_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Sample name', max_length=50, verbose_name='Name')),
                ('author_desc', models.CharField(default='Sample desc', max_length=1000, verbose_name='Description')),
                ('author_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Birth date')),
                ('author_death', models.DateField(blank=True, default='', verbose_name='Death date')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.CharField(choices=[('Einst', 'Albert Einstein'), ('Zveist', 'Antonio Zveistein'), ('Dreist', 'Anatolio Dreistein')], default='No author was added.', max_length=50, verbose_name='Author'),
        ),
    ]
