# Generated by Django 5.0.6 on 2024-06-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_post_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
