# Generated by Django 5.0.6 on 2024-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_tag_tag_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_birth_place',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Place of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_birth_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', 10), ('11', 11), ('12', 12)], default='-', max_length=15, verbose_name='Birth month'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_death_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', 10), ('11', 11), ('12', 12)], default='-', max_length=15, verbose_name='Death month'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_desc',
            field=models.CharField(default='Sample desc', max_length=5000, verbose_name='Description'),
        ),
    ]
