# Generated by Django 5.0.6 on 2024-06-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_author_author_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(default='No text was added.', max_length=1500, verbose_name='Quote'),
        ),
    ]
